/** Declaration file generated by dts-gen */

export function extract(str: any): any;

export function parse(str: any, opts: any): any;

export function parseUrl(str: any, opts: any): object;

export function stringify(obj: any, opts: any): string;

export namespace extract {
    const prototype: {
    };

}

export namespace parse {
    const prototype: {
    };

}

export namespace parseUrl {
    const prototype: {
    };

}

export namespace stringify {
    const prototype: {
    };

}

